enum ErrorTypes {
  USERNAME_OR_PASSWORD_IS_REQUIRED = 0,
  USERNAME_EXISTS = 1,
  USERNAME_NOT_EXISTS = 2,
  PASSWORD_ERROR = 3,
  UNAUTHORIZATION = 4,
  REQUIRE_HAVA_VALUE = 5,
}

export default ErrorTypes
